import os
import serial

# SYNC PRINTER BAUDRATE 115.2KBPS
BAUD_RATE = 115200

# SERIAL PORTS - CHECK PORT AVAILABILITY WITH "ls -l/dev/tty*" IN TERMINAL
RTOS_PATH = "/dev/ttyAMA1"
LINUX_PATH = "/dev/ttyAMA2"

# DEFINE pySerial OBJECT TO SET UP SEPARATE SERIAL PORT CONNECTIONS
RTOS = serial.Serial(port=RTOS_PATH, baudrate=BAUD_RATE, timeout=5)
LINUX = serial.Serial(port=LINUX_PATH, baudrate=BAUD_RATE, timeout=5)

# USER API DIRECTORY
USER_DIRECTORY = os.getcwd() + '/user'

RTOS_LOG_FILE_PATH = 'logs/seriallog.txt'
LINUX_LOG_FILE_PATH = 'logs/linuxlog.txt'
CONSOLE_LOG_FILE_PATH = 'logs/consolelog.txt'
COMMAND_LOG_FILE_PATH = 'logs/commandlog.txt'

RTOS_MODE = 0
LINUX_MODE = 1
AUTO_MODE = 2

RTOS_PREPEND_INDICATOR = "#"
LINUX_PREPEND_INDICATOR = "X"
AUTO_PREPEND_INDICATOR = "AUTO"

# MINICIRCUITS WIFI ATTENUATOR PARAMS
VENDOR_ID = 0x20CE
PRODUCT_ID = 0x0023

# SCPI COMMANDS
GET_SN = "*:SN?"
GET_MN = "*:MN?"
GET_FW = "*:FIRMWARE?"

INIT_MAX_ATT_CHAN_FOUR = "*:CHAN:4:SETATT:95"
INIT_ATT_ALL_CHAN = ":*CHAN:1:2:3:SETATT:0"

GET_ATT = "*:ATT?"
SET_ALL_ATT = "*:CHAN:1:2:3:SETATT:{0}"

# CH4 NOT CONNECTED CH4 SET TO 90
in_progress_flag = 0